ILink/ILink/urls.py
from django.conf.urls import url , include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/' , include('accounts.urls', namespace='accounts')),
    url(r'^projects/' , include('projects.urls', namespace='projects'))
]

ILink/accounts/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounts'

urlpatterns = [
	url(r'^$' , views.index , name = 'index') ,
	url(r'^register$' , views.register , name = 'register') ,
	url(r'^login$' , views.login , name = 'login') ,
	url(r'^home$' , views.home , name='home'),
	url(r'^index$' , views.logout , name='logout'),
	url(r'^setting$' , views.settingProfile , name='settingProfile'),
	url(r'^setting/experience$' , views.settingExperience , name='settingExperience'),
	url(r'^setting/experience/(?P<experience_id>[0-9]*)$' , views.deleteExperience , name = 'deleteExperience'),
	url(r'^setting/skill$' , views.settingSkill , name='settingSkill'),
	url(r'^setting/skill/(?P<skill_id>[0-9]*)$' , views.deleteSkill , name='deleteSkill'),
	url(r'^resume$' , views.showResume , name='showResume'),
	url(r'^resume/(?P<account_id>[0-9]*)$' , views.showResumeWithID , name='showResumeWithID'),
]

ILink/accounts/models.py
from __future__ import unicode_literals
from datetime import datetime

from django.db import models

# Account for user login
class Account(models.Model):
	"""
	Account informations for users

	"""
	# Account info for register & login
	_account_name = models.CharField(max_length = 30 , unique = True )
	_account_passwd = models.CharField(max_length = 50)
	_account_register_date = models.DateField()
	

	@property
	def account_name(self):
	    return self._account_name
	
	@property
	def account_passwd(self):
	    return self._account_passwd
	@account_passwd.setter
	def account_passwd(self , new_password) :
		self._account_passwd = new_password
	
	@property
	def account_register_date(self):
	    return self._account_register_date
	
	@classmethod
	def create(cls , name , password) :
		account = cls(_account_name = name , _account_passwd = password)
		account._account_register_date = datetime.now()
		return account


	# Representations
	def __str__(self) :
		account_info = 'Account: ' + self._account_name
		return account_info
	__repr__ = __str__

# Contact info , one to one relation to user account
class ContactInfo(models.Model) :
	'''
	Contact information for users...
	One to one relationship to Account

	'''

	account = models.OneToOneField(
		Account,
		on_delete = models.CASCADE,
		primary_key=True,
	)

	_contactinfo_name = models.CharField(max_length=30, blank=True)
	_contactinfo_cellphone = models.CharField(max_length=20 , blank=True)
	_contactinfo_birthdate = models.CharField(max_length=50,blank=True)
	_contactinfo_gender = models.CharField(max_length=30 , blank=True)
	_contactinfo_address = models.CharField(max_length=50 , blank=True)
	_contactinfo_description = models.CharField(max_length = 140 ,blank=True)

	# Properties & setter
	@property
	def contactinfo_name(self):
	    return self._contactinfo_name
	@contactinfo_name.setter
	def contactinfo_name(self , name) :
		self._contactinfo_name = name
	@property
	def contactinfo_cellphone(self):
	    return self._contactinfo_cellphone
	@contactinfo_cellphone.setter
	def contactinfo_cellphone(self , phonenum) :
		self._contactinfo_cellphone = phonenum
	@property
	def contactinfo_birthdate(self):
	    return self._contactinfo_birthdate
	@contactinfo_birthdate.setter
	def contactinfo_birthdate(self , birthdate) :
		self._contactinfo_birthdate = birthdate
	@property
	def contactinfo_gender(self):
	    return self._contactinfo_gender
	@contactinfo_gender.setter
	def contactinfo_gender(self , gender):
		self._contactinfo_gender = gender
	@property
	def contactinfo_address(self):
	    return self._contactinfo_address
	@contactinfo_address.setter
	def contactinfo_address(self,  addr):
		self._contactinfo_address = addr
	@property
	def contactinfo_description(self):
	    return self._contactinfo_description
	@contactinfo_description.setter
	def contactinfo_description(self , description):
		self._contactinfo_description = description

	@classmethod
	def create(cls , account, name , phonenum  , birthdate,
		gender , address , description) :
		contact_info = cls(account = account , _contactinfo_name = name , _contactinfo_cellphone = phonenum , 
			_contactinfo_birthdate = birthdate , _contactinfo_gender = gender ,
			_contactinfo_address = address , _contactinfo_description = description)
		return contact_info

	# properties update
	def update_contact_info(self , name , phonenum ,  birthdate ,
		gender , address , description) :
		self._contactinfo_name = name
		self._contactinfo_cellphone = phonenum
		self._contactinfo_birthdate = birthdate
		self._contactinfo_gender = gender
		self._contactinfo_address = address
		self._contactinfo_description = description

	# Representations
	def __str__(self) :
		return 'Contact Info of:' + self._contactinfo_name + ' from account : ' + account.account_name
	__repr__ = __str__

# Experience info , many to one relation to user account
class Experience(models.Model) :
	'''
	Experience info for users...
	Many to one relationship to Account

	'''
	account = models.ForeignKey(
		Account,
		on_delete = models.CASCADE
	)

	_job_title = models.CharField(max_length=30 , default='Null')
	_description = models.TextField(default='Null')
	_start_date = models.DateField(blank=True)
	_end_date = models.DateField(blank=True)

	# Properties & setter
	@property
	def job_title(self):
	    return self._job_title
	@job_title.setter
	def job_title(self , title) :
		self._job_title = title
	@property
	def description(self):
	    return self._description
	@description.setter
	def description(self , description):
		self._description = description
	@property
	def start_date(self):
	    return self._start_date
	@start_date.setter
	def start_date(self , date):
		self._start_date = date
	@property
	def end_date(self):
	    return self._end_date
	@end_date.setter
	def end_date(self , date):
		self._end_date = date

	@classmethod
	def create(cls , account , job_title , description , start_date , end_date) :
		experience = cls(account = account , _job_title = job_title , _description = description,
			_start_date = start_date , _end_date = end_date)
		return experience

	# properties update
	def update_experience(job_title , description , start_date , end_date) :
		self._job_title = job_title
		self._description = description
		self._start_date = start_date
		self._end_date = end_date

	# Representations
	def __str__(self) :
		return 'Experience of :' + self._job_title + ' for account:' + account.account_name
	__repr__ = __str__
	
# Skills info , many to one relation to Account
class Skill(models.Model) :
	account = models.ForeignKey(
		Account,
		on_delete = models.CASCADE
	)

	_skill_type = models.CharField(max_length=30 , default='Null')
	_skill_proficiency = models.IntegerField(default=5)
	_skill_description = models.TextField(default='Null')

	# Properties & setter
	@property
	def skill_type(self):
	    return self._skill_type
	@skill_type.setter
	def skill_type(self , skill) :
		self._skill_type = skill
	@property
	def skill_proficiency(self):
	    return self._skill_proficiency
	@skill_proficiency.setter
	def skill_proficiency(self , proficiency) :
		self._skill_proficiency = proficiency
	@property
	def skill_description(self):
	    return self._skill_description
	@skill_description.setter
	def skill_description(self , description):
		self._skill_description = description

	@classmethod
	def create(cls , account , skill_type , skill_proficiency , skill_description):
		skill = cls(account = account_name , _skill_type = skill_type ,
			_skill_proficiency = skill_proficiency, _skill_description = skill_description)
		return skill

	# properties update
	def update_skill(skill_type , skill_proficiency , skill_description) :
		self._skill_type = skill_type
		self._skill_proficiency = skill_proficiency
		self._skill_description = skill_description

	# Representations
	def __str__(self) :
		return 'Skill:' + self._skill_type + ' of account :' + self.account.account_name
	__repr__ = __str__

ILink/accounts/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

import hashlib
import datetime

from .models import Account , ContactInfo

def index(request) :
	return render(request , 'home.html')

# Unfinished
def settingProfile(request) :
	# validate user session
	try:
		account = Account.objects.get(_account_name = request.session['account_name'])
	except Exception, e:
		return render(request , 'accounts/login.html' , {
			'is_login_success' : False,
			'is_register_success' : False,
			'is_first_time_to_this_page' : False,
			})

	#import pdb; pdb.set_trace()

	if not hasattr(account , 'contactinfo') :
		ContactInfo.objects.create( account = account ,
			_contactinfo_name = '' , _contactinfo_gender = '' ,
			_contactinfo_birthdate = datetime.datetime.today() , 
			_contactinfo_cellphone = '' , _contactinfo_address = '' , 
			_contactinfo_description = '')

	# check profile info
	try:
		user_name = request.POST['username']
		if request.POST['gender'] == 'Option one' :
			user_gender = 'Male'
		else :
			user_gender = 'Female'
		user_birthdate = request.POST['birthdate']
		user_cellphone = request.POST['cellphone']
		user_address = request.POST['address']
		user_description = request.POST['description']

		account.contactinfo.update_contact_info(user_name , user_cellphone ,
			user_birthdate , user_gender , user_address , user_description)
		account.contactinfo.save()

	except Exception, e:
		return render(request , 'accounts/setting/profile.html',{
		'is_login_success' : True,
		'user_session' : account,
		'contactinfo' : account.contactinfo
		})
		
	

	return render(request , 'accounts/setting/profile.html',{
		'is_login_success' : True,
		'user_session' : account,
		'contactinfo' : account.contactinfo
		})

def settingExperience(request) :
	# validate user session
	try:
		account = Account.objects.get(_account_name = request.session['account_name'])
	except Exception, e:
		return render(request , 'accounts/login.html' , {
			'is_login_success' : False,
			'is_register_success' : False,
			'is_first_time_to_this_page' : False,
			})

	# Fetch user configuration
	try:
		job_title = request.POST['title']
		start_date = datetime.datetime.strptime(request.POST['startDate'] , '%d-%m-%Y')
		end_date = datetime.datetime.strptime(request.POST['endDate'] , '%d-%m-%Y')
		job_description = request.POST['description']

		account.experience_set.create(_job_title = job_title , _description = job_description , 
			_start_date = start_date , _end_date = end_date)
	except Exception, e:
		# representation page
		return render(request , 'accounts/setting/experience.html',{
		'is_login_success' : True,
		'user_session' : account,
		'user_experience_list' : account.experience_set.all().order_by('-_start_date'),
		})	
	
	return render(request , 'accounts/setting/experience.html',{
		'is_login_success' : True,
		'user_session' : account,
		'user_experience_list' : account.experience_set.all().order_by('-_start_date'),
		})

def deleteExperience(request , experience_id):
	# validate user session
	try:
		account = Account.objects.get(_account_name = request.session['account_name'])
	except Exception, e:
		return render(request , 'accounts/login.html' , {
			'is_login_success' : False,
			'is_register_success' : False,
			'is_first_time_to_this_page' : False,
			})

	# Delete
	experience_for_delete = account.experience_set.filter(id = experience_id)
	for experience in experience_for_delete :
		experience.delete()

	return HttpResponseRedirect('/accounts/setting/experience')

def settingSkill(request) :
	# validate user session
	try:
		account = Account.objects.get(_account_name = request.session['account_name'])
	except Exception, e:
		return render(request , 'accounts/login.html' , {
			'is_login_success' : False,
			'is_register_success' : False,
			'is_first_time_to_this_page' : False,
			})

	# Fetch user configuration
	try:
		skill_type = request.POST['skill_type']
		skill_proficiency = request.POST['skill_proficiency']
		skill_description = request.POST['skill_description']
		account.skill_set.create(_skill_type = skill_type , _skill_proficiency=skill_proficiency , _skill_description = skill_description)
	except Exception, e:
		# representation page
		return render(request , 'accounts/setting/skill.html',{
		'is_login_success' : True,
		'user_session' : account,
		'user_skill_list' : account.skill_set.all().order_by('-_skill_proficiency'),
		})	
	
	return render(request , 'accounts/setting/skill.html',{
		'is_login_success' : True,
		'user_session' : account,
		'user_skill_list' : account.skill_set.all().order_by('-_skill_proficiency'),
		})

def deleteSkill(request , skill_id):
	# validate user session
	try:
		account = Account.objects.get(_account_name = request.session['account_name'])
	except Exception, e:
		return render(request , 'accounts/login.html' , {
			'is_login_success' : False,
			'is_register_success' : False,
			'is_first_time_to_this_page' : False,
			})

	# Delete
	skill_for_delete = account.skill_set.filter(id = skill_id)
	for skill in skill_for_delete :
		skill.delete()

	return HttpResponseRedirect('/accounts/setting/skill')

def home(request) :
	# validate user session
	try:
		account = Account.objects.get(_account_name = request.session['account_name'])
	except Exception, e:
		return render(request , 'accounts/login.html' , {
			'is_login_success' : False,
			'is_register_success' : False,
			'is_first_time_to_this_page' : False,
			})

	return render(request , 'home.html' , {
			'is_login_success' : True,
			'user_session' : account,
			})

def logout(request):
	del request.session['account_name']
	return render(request , 'home.html')

def register(request) :

	is_register_success = False

	# Fetch register information
	try :
		account_name = request.POST['account_name']
		account_password = request.POST['account_password']
		if '' == account_name or '' == account_password :
			raise KeyError('Invalid account')
	except (KeyError):
		return render(request , 'accounts/register.html' , {
			'is_register_success' : is_register_success ,
			'is_first_time_to_this_page' : True,
			})

	# Encode account password
	md5 = hashlib.md5()
	md5.update(account_password.encode('utf-8'))
	account_password = md5.hexdigest()

	# Create new account
	new_account = Account.create(account_name , account_password)
	try :
		new_account.save()
	except BaseException  :
		return render(request , 'accounts/register.html' , {
			'is_register_success' : is_register_success ,
			'is_first_time_to_this_page' : False,
			})

	# Success		
	is_register_success = True	

	return render(request , 'accounts/login.html' , {
		'is_register_success' : True,
		'is_first_time_to_this_page' : False,
		})

def login(request) :

	is_login_success = False

	# Fetch user configuration
	try:
		account_name = request.POST['account_name']
		account_password = request.POST['account_password']
		if '' == account_name or '' == account_password :
			raise KeyError('Invalid input')
	except(KeyError):
		return render(request , 'accounts/login.html' , {
			'is_login_success' : False,
			'is_register_success' : False,
			'is_first_time_to_this_page' : True,
			})

	# Encode account password
	md5 = hashlib.md5()
	md5.update(account_password.encode('UTF-8'))
	account_password = md5.hexdigest()

	# Account validation
	try:
		account_for_validation = Account.objects.get(_account_name = account_name)
	except Exception, e:
		return render(request , 'accounts/login.html' , {
			'is_login_success' : False,
			'is_register_success' : False,
			'is_first_time_to_this_page' : False,
			})
		
	
	if account_for_validation :
		if account_for_validation.account_passwd == account_password :
			is_login_success = True
			
			request.session['account_name'] = account_name
			request.session.SESSION_EXPIRE_AT_BROWSER_CLOSE = True

			return render(request , 'home.html' , {
			'is_login_success' : is_login_success,
			'user_session' : Account.objects.get(_account_name = account_name),
			})

	return render(request , 'accounts/login.html' , {
			'is_login_success' : False,
			'is_register_success' : False,
			'is_first_time_to_this_page' : False,
			})

def showResume(request) :
	# validate user session
	try:
		account = Account.objects.get(_account_name = request.session['account_name'])
	except Exception, e:
		return render(request , 'accounts/login.html' , {
			'is_login_success' : False,
			'is_register_success' : False,
			'is_first_time_to_this_page' : False,
			})

	return render(request , 'accounts/resume.html',{
		'is_login_success' : True,
		'user_session' : account,
		'request_user' : account,
		'user_skill_list' : account.skill_set.all().order_by('-_skill_proficiency'),
		'user_experience_list' : account.experience_set.all().order_by('-_start_date'),
		})

def showResumeWithID(request, account_id):
	# validate user session
	try:
		account = Account.objects.get(_account_name = request.session['account_name'])
	except Exception, e:
		return render(request , 'accounts/login.html' , {
			'is_login_success' : False,
			'is_register_success' : False,
			'is_first_time_to_this_page' : False,
			})

	try:
		request_account = Account.objects.get(id=account_id)
	except Exception, e:
		return HttpResponseRedirect('/accounts/resume')

	return render(request , 'accounts/resume.html',{
		'is_login_success' : True,
		'user_session' : account,
		'request_user' : request_account,
		'user_skill_list' : request_account.skill_set.all().order_by('-_skill_proficiency'),
		'user_experience_list' : request_account.experience_set.all().order_by('-_start_date'),
		})
	

ILink/accounts/templates/accounts/setting/experience.html
{% extends 'home.html' %}

{% block head %}
<!-- <link href="/static/css/timePicker.css" rel="stylesheet"> -->
<link href="/static/bootstrap/css/bootstrap-datetimepicker.min.css" rel="stylesheet" media="screen">
{% endblock %}

{% block content %}
<header id="head" class="secondary"></header>
<br/>
<div class="container" >
	<div class="row">
		<div class="span2 col-md-3 col-md-offset-1">
			<ul class="nav nav-pills nav-stacked"> 
				<li><a href={% url 'accounts:settingProfile' %}>Profile</a></li>
				<li><a href={% url 'accounts:settingSkill' %}>Skill</a></li> 
				<li class="active"><a href={% url 'accounts:settingExperience' %}>Experience</a></li> 
			</ul>
		</div>
		<div class="col-md-7">
		      <table class="table table-hover ">
				   <caption></caption>
				   <thead>
				      <tr>
				         <th>Job Title</th>
				         <th>Duration</th>
				         <th>Description</th>
				      </tr>
				   </thead>
				   <tbody>
				   {% for experience in user_experience_list %}
				      <tr>
				         <td>{{experience.job_title}}</td>
				         <td>{{experience.start_date}} - {{experience.end_date}}</td>
				         <td>{{experience.description}}</td>
				         <td style="text-align:center;">
				   			<a href={% url 'accounts:deleteExperience' experience.id %}>
  								<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
							</a>
						</td>
				      </tr>
				    {% endfor %}
				   </tbody>
				</table>

				<br/><br/>

	<form class="form-horizontal" action="{% url 'accounts:settingExperience'%}" method="POST">
	{% csrf_token %}
	  <fieldset>
		<a class="btn " type="button" data-toggle="collapse" data-target="#addExperience" aria-expanded="false" aria-controls="addExperience" style="position: relative;left:33%;">
		  Add Experience
		</a>
		<div class="collapse" id="addExperience">
 		 <div class="well">

    		<div class="control-group">
	      <!-- Text input-->
		      <label class="control-label" for="input01">Title</label>
		      <div class="controls">
		        <input type="text" name = "title" placeholder="title" class="input-xlarge form-control">
		        <p class="help-block"> </p>
		      </div>
		    </div>

			<!--  <div class="control-group">
				   <label class="control-label">Duration</label>
				  <div class="controls">
				<div id='wrapper'>
 						 <select class='custom-date form-control' name='select'>
 					      <option value='7'>7 Days</option>
 					      <option value='30'>30 Days</option>
 					      <option selected='selected' value='90'>90 Days</option>
 					      <option value='180'>180 Days</option>
 					      <option value='365'>365 Days</option>
 					      <option value='custom'>Custom</option>
 					    </select>
 					</div>
		   		  <p class="help-block"></p>
				  </div>
				</div> -->
				<div class="control-group">
	                <label for="dtp_input2" class="control-label">Start Time</label>
	                <div class="input-group date form_date" data-date="" data-date-format="dd-mm-yyyy" data-link-field="dtp_input2" data-link-format="yyyy-mm-dd">
	                    <input id="startTime" name = "startDate" class="form-control" size="16" type="text" value="" readonly>
	                    <span class="input-group-addon">
	                    	<span class="glyphicon glyphicon-remove"></span>
	                    </span>
	                    <span class="input-group-addon">
	            		    <span class="glyphicon glyphicon-calendar"></span>
	            		</span>
	                </div>
					<p class="help-block"></p>
          	 	 </div>			

			<div class="control-group">
	                <label for="dtp_input2" class="control-label">End Time</label>
	                <div class="input-group date form_date" data-date="" data-date-format="dd-mm-yyyy" data-link-field="dtp_input2" data-link-format="yyyy-mm-dd">
	                    <input id="endTime" name = "endDate" class="form-control" size="16" type="text" value="" readonly>
	                     <span class="input-group-addon">
	                    	<span class="glyphicon glyphicon-remove"></span>
	                    </span>
	                    <span class="input-group-addon">
	            		    <span class="glyphicon glyphicon-calendar"></span>
	            		</span>
	                </div>
					<p class="help-block"></p>
          	 	 </div>			

			 <div class="control-group">
		      <!-- Textarea -->
		      <label class="control-label">Description</label>
		      <div class="controls">
		        <div class="textarea">
		              <textarea name = "description" type="" class="form-control"> </textarea>
		        </div>
		        <p class="help-block"></p>
		      </div>
		    </div>

		     <div class="control-group">
		          <label class="control-label"> </label>
		          <!-- Button -->
		          <div class="controls">
		            <button class="btn btn-success">+</button>
		          </div>
		          <p class="help-block"></p>
		     </div>
		 </div>
		</div>
		
	 </fieldset>
	 </form>

		</div>
	</div>
</div>


{% endblock %}


{% block footer %}
	<footer id="footer" class="top-space">
	  <nav class="navbar-default navbar-fixed-bottom">
		<div class="footer2">
			<div class="container">
				<div class="row">				
					<div class="col-md-6 widget">
						<div class="widget-body">
							<p class="simplenav" stlye="">
								{% if is_login_success %}
								<a href={% url 'accounts:home' %} >Home</a> | 
								<a href="#">Project</a> |
								<a id="setting" href={% url 'accounts:settingProfile' %} >Setting</a> 
								|
								<a id="logout" href={% url 'accounts:logout' %} >Logout</a> 
								{% else %}
								<b><a href={% url 'accounts:register'%}>Sign up</a></b>
								{% endif %}
								| 
								<a href="javascript:scroll(0,0)">
								<span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span>
								</a>
							</p>
						</div>
					</div>
				</div> <!-- /row of widgets -->
			</div>
		</div>
	 </nav>
	</footer>	
	{% endblock %}


{% block js %}
{% load static %}
<!-- <script src="{% static "js/timePicker.js" %}"></script> -->
<script src="{% static "bootstrap/js/bootstrap-datetimepicker.js" %}"></script>

<script type="text/javascript">
	$('.form_date').datetimepicker({
        language:  'fr',
        weekStart: 1,
        todayBtn:  1,
		autoclose: 1,
		todayHighlight: 1,
		startView: 2,
		minView: 2,
		forceParse: 0
    });
</script>
{% endblock %}

ILink/accounts/templates/accounts/setting/skill.html
{% extends 'home.html' %}
{% block head %}
<link href="/static/bootstrap/css/bootstrap-slider.min.css" rel="stylesheet">
<style type='text/css'>
.slider-handle.custom {
background: transparent none;
}
</style>
{% endblock %}

{% block content %}
<header id="head" class="secondary"></header>
<br/>
<div class="container">
	<div class="row">
		<div class="span2 col-md-3 col-md-offset-1">
			<ul class="nav nav-pills nav-stacked"> 
				<li><a href={% url 'accounts:settingProfile' %}>Profile</a></li>
				<li class="active"><a href={% url 'accounts:settingSkill' %}>Skill</a></li> 
				<li><a href={% url 'accounts:settingExperience' %}>Experience</a></li> 
			</ul>
		</div>
		<div class="col-md-7 ">
		      <table class="table table-hover ">
				   <caption></caption>
				   <thead >
				      <tr>
				         <th>Skill</th>
				         <th>Proficiency</th>
				         <th>Description</th>
				      </tr>
				   </thead>

				   <tbody>
				   {% for skill in user_skill_list %}
				   <tr>
				   		<td>{{ skill.skill_type }}</td>
						<td>{{ skill.skill_proficiency }}</td>
				   		<td>{{ skill.skill_description }}</td>
				   		<td style="text-align:center;">
				   			<a href={% url 'accounts:deleteSkill' skill.id %}>
  								<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
							</a>
						</td>
				   </tr>
				   {% endfor %}
				   </tbody>
				</table>

		<br/><br/>

		<form class="form-horizontal" action="{% url 'accounts:settingSkill' %}" method="POST">
		{% csrf_token %}
		  <fieldset>
			<a class="btn " type="button" data-toggle="collapse" data-target="#addExperience" aria-expanded="false" aria-controls="addExperience" style="position: relative;left:35%;">
			  Add Skill
			</a>
			<div class="collapse" id="addExperience">
	 		 <div class="well">

	    		<div class="control-group">
		      <!-- Text input-->
			      <label class="control-label" for="input01">Skill</label>
			      <div class="controls">
			        <input type="text" id = "_skill_type" name = "skill_type" placeholder="skill type" class="input-xlarge form-control">
			        <p class="help-block"> </p>
			        <p class="help-block"> </p>
			      </div>
		 	    </div>
			   
			   <div class="control-group">
	 	      <!-- Text input-->
	 		      <label class="control-label" for="input01">Proficiency</label>
	 			  <div class="controls">
	 				<input id="proficiency" name="skill_proficiency" data-slider-handle="custom" type="text" data-slider-min="1" data-slider-max="10" data-slider-step="1" data-slider-value="5"/>
	 			  </div>
	 		    
	 		    </div>

			    <div class="control-group">
		      <!-- Text input-->
			      <label class="control-label" for="input01">Description</label>
			      <div class="textarea">
					<textarea id="_skill_description" name = "skill_description" type="" placeholder="skill description" class="form-control" /></textarea>
				  </div>
			    </div>


			     <div class="control-group">
			          <label class="control-label"> </label>
			          <!-- Button -->
			          <div class="controls">
			            <button class="btn btn-success">+</button>
			          </div>
			          <p class="help-block"></p>
			     </div>
			 </div>
			</div>
			
		 </fieldset>
		 </form>
		</div>
	</div>
</div>

{% endblock %}

{% block footer %}
	<footer id="footer" class="top-space">
	  <nav class="navbar-default navbar-fixed-bottom">
		<div class="footer2">
			<div class="container">
				<div class="row">				
					<div class="col-md-6 widget">
						<div class="widget-body">
							<p class="simplenav" stlye="">
								{% if is_login_success %}
								<a href={% url 'accounts:home' %} >Home</a> | 
								<a href="#">Project</a> |
								<a id="setting" href={% url 'accounts:settingProfile' %} >Setting</a> 
								|
								<a id="logout" href={% url 'accounts:logout' %} >Logout</a> 
								{% else %}
								<b><a href={% url 'accounts:register'%}>Sign up</a></b>
								{% endif %}
								| 
								<a href="javascript:scroll(0,0)">
								<span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span>
								</a>
							</p>
						</div>
					</div>
				</div> <!-- /row of widgets -->
			</div>
		</div>
	 </nav>
	</footer>	
{% endblock %}

{% block js %}

{% load static %}
<script src="{% static "bootstrap/js/bootstrap-slider.min.js" %}"></script>

<script type='text/javascript'>
    	$(document).ready(function() {
	        $("#proficiency").slider({
	tooltip: 'always'
});
	    })
</script>
{% endblock %}