ILink/ILink/urls.py
from django.conf.urls import url , include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/' , include('accounts.urls', namespace='accounts')),
    url(r'^projects/' , include('projects.urls', namespace='projects'))
]

ILink/accounts/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounts'

urlpatterns = [
	url(r'^$' , views.index , name = 'index') ,
	url(r'^register$' , views.register , name = 'register') ,
	url(r'^login$' , views.login , name = 'login') ,
	url(r'^home$' , views.home , name='home'),
	url(r'^index$' , views.logout , name='logout'),
	url(r'^setting$' , views.settingProfile , name='settingProfile'),
	url(r'^setting/experience$' , views.settingExperience , name='settingExperience'),
	url(r'^setting/experience/(?P<experience_id>[0-9]*)$' , views.deleteExperience , name = 'deleteExperience'),
	url(r'^setting/skill$' , views.settingSkill , name='settingSkill'),
	url(r'^setting/skill/(?P<skill_id>[0-9]*)$' , views.deleteSkill , name='deleteSkill'),
	url(r'^resume$' , views.showResume , name='showResume'),
	url(r'^resume/(?P<account_id>[0-9]*)$' , views.showResumeWithID , name='showResumeWithID'),
]

ILink/projects/urls.py
from django.conf.urls import url

from . import views

app_name = 'projects'

urlpatterns = [
	url(r'^$' , views.myProjects , name = 'myProjects') ,
	url(r'^wechattest$' , views.wechattest , name = 'wechattest') ,
	url(r'^wechatredirect$' , views.wechatredirect , name = 'wechatredirect') ,
	url(r'^myApplications$' , views.myApplications , name = 'myApplications') ,
	url(r'^projectsByType/(?P<type>\w*)$' , views.projectsByType , name = 'projectsByType') ,
	url(r'^projectDetail$' , views.projectDetail , name='projectDetail'),
	url(r'^quickCreate$' , views.projectQuickCreate , name = 'projectQuickCreate'),
	url(r'^projectDetail/(?P<project_id>[0-9]*)$' , views.project_details , name = 'projectDetailsById'),
	url(r'^projectDetail/(?P<project_id>[0-9]*)/createTask$' , views.create_task , name = 'createTask'),
	url(r'^projectDetail/(?P<project_id>[0-9]*)/deleteTask/(?P<task_id>[0-9]*)$' , views.delete_task , name = 'deleteTask'),
	url(r'^projectDetail/(?P<project_id>[0-9]*)/addMember$' , views.add_member , name = 'addMember'),
	url(r'^projectDetail/(?P<project_id>[0-9]*)/deleteMember/(?P<member_id>[0-9]*)$' , views.delete_member , name = 'deleteMember'),
	url(r'^findProject$' , views.findProject , name = 'findProject'),
	url(r'^applyProject/(?P<project_id>[0-9]*)$' , views.applyProject , name = 'applyProject'),
	url(r'^applyForProject/(?P<project_id>[0-9]*)$' , views.applyForProject , name = 'applyForProject'),
	url(r'^reviewProject/(?P<project_id>[0-9]*)$' , views.reviewProject , name = 'reviewProject'),
	url(r'^projectDetail/(?P<project_id>[0-9]*)/changeTask/(?P<task_id>[0-9]*)$' , views.change_task , name = 'changeTask'),
	url(r'^projectDetail/(?P<project_id>[0-9]*)/addApplicant/(?P<member_id>[0-9]*)$' , views.addApplicant , name = 'addApplicant'),
	url(r'^projectDetail/(?P<project_id>[0-9]*)/deleteApplicant/(?P<member_id>[0-9]*)$' , views.deleteApplicant , name = 'deleteApplicant'),

]

ILink/accounts/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

import hashlib
import datetime

from .models import Account , ContactInfo

def index(request) :
	return render(request , 'home.html')

# Unfinished
def settingProfile(request) :
	# validate user session
	try:
		account = Account.objects.get(_account_name = request.session['account_name'])
	except Exception, e:
		return render(request , 'accounts/login.html' , {
			'is_login_success' : False,
			'is_register_success' : False,
			'is_first_time_to_this_page' : False,
			})

	#import pdb; pdb.set_trace()

	if not hasattr(account , 'contactinfo') :
		ContactInfo.objects.create( account = account ,
			_contactinfo_name = '' , _contactinfo_gender = '' ,
			_contactinfo_birthdate = datetime.datetime.today() , 
			_contactinfo_cellphone = '' , _contactinfo_address = '' , 
			_contactinfo_description = '')

	# check profile info
	try:
		user_name = request.POST['username']
		if request.POST['gender'] == 'Option one' :
			user_gender = 'Male'
		else :
			user_gender = 'Female'
		user_birthdate = request.POST['birthdate']
		user_cellphone = request.POST['cellphone']
		user_address = request.POST['address']
		user_description = request.POST['description']

		account.contactinfo.update_contact_info(user_name , user_cellphone ,
			user_birthdate , user_gender , user_address , user_description)
		account.contactinfo.save()

	except Exception, e:
		return render(request , 'accounts/setting/profile.html',{
		'is_login_success' : True,
		'user_session' : account,
		'contactinfo' : account.contactinfo
		})
		
	

	return render(request , 'accounts/setting/profile.html',{
		'is_login_success' : True,
		'user_session' : account,
		'contactinfo' : account.contactinfo
		})

def settingExperience(request) :
	# validate user session
	try:
		account = Account.objects.get(_account_name = request.session['account_name'])
	except Exception, e:
		return render(request , 'accounts/login.html' , {
			'is_login_success' : False,
			'is_register_success' : False,
			'is_first_time_to_this_page' : False,
			})

	# Fetch user configuration
	try:
		job_title = request.POST['title']
		start_date = datetime.datetime.strptime(request.POST['startDate'] , '%d-%m-%Y')
		end_date = datetime.datetime.strptime(request.POST['endDate'] , '%d-%m-%Y')
		job_description = request.POST['description']

		account.experience_set.create(_job_title = job_title , _description = job_description , 
			_start_date = start_date , _end_date = end_date)
	except Exception, e:
		# representation page
		return render(request , 'accounts/setting/experience.html',{
		'is_login_success' : True,
		'user_session' : account,
		'user_experience_list' : account.experience_set.all().order_by('-_start_date'),
		})	
	
	return render(request , 'accounts/setting/experience.html',{
		'is_login_success' : True,
		'user_session' : account,
		'user_experience_list' : account.experience_set.all().order_by('-_start_date'),
		})

def deleteExperience(request , experience_id):
	# validate user session
	try:
		account = Account.objects.get(_account_name = request.session['account_name'])
	except Exception, e:
		return render(request , 'accounts/login.html' , {
			'is_login_success' : False,
			'is_register_success' : False,
			'is_first_time_to_this_page' : False,
			})

	# Delete
	experience_for_delete = account.experience_set.filter(id = experience_id)
	for experience in experience_for_delete :
		experience.delete()

	return HttpResponseRedirect('/accounts/setting/experience')

def settingSkill(request) :
	# validate user session
	try:
		account = Account.objects.get(_account_name = request.session['account_name'])
	except Exception, e:
		return render(request , 'accounts/login.html' , {
			'is_login_success' : False,
			'is_register_success' : False,
			'is_first_time_to_this_page' : False,
			})

	# Fetch user configuration
	try:
		skill_type = request.POST['skill_type']
		skill_proficiency = request.POST['skill_proficiency']
		skill_description = request.POST['skill_description']
		account.skill_set.create(_skill_type = skill_type , _skill_proficiency=skill_proficiency , _skill_description = skill_description)
	except Exception, e:
		# representation page
		return render(request , 'accounts/setting/skill.html',{
		'is_login_success' : True,
		'user_session' : account,
		'user_skill_list' : account.skill_set.all().order_by('-_skill_proficiency'),
		})	
	
	return render(request , 'accounts/setting/skill.html',{
		'is_login_success' : True,
		'user_session' : account,
		'user_skill_list' : account.skill_set.all().order_by('-_skill_proficiency'),
		})

def deleteSkill(request , skill_id):
	# validate user session
	try:
		account = Account.objects.get(_account_name = request.session['account_name'])
	except Exception, e:
		return render(request , 'accounts/login.html' , {
			'is_login_success' : False,
			'is_register_success' : False,
			'is_first_time_to_this_page' : False,
			})

	# Delete
	skill_for_delete = account.skill_set.filter(id = skill_id)
	for skill in skill_for_delete :
		skill.delete()

	return HttpResponseRedirect('/accounts/setting/skill')

def home(request) :
	# validate user session
	try:
		account = Account.objects.get(_account_name = request.session['account_name'])
	except Exception, e:
		return render(request , 'accounts/login.html' , {
			'is_login_success' : False,
			'is_register_success' : False,
			'is_first_time_to_this_page' : False,
			})

	return render(request , 'home.html' , {
			'is_login_success' : True,
			'user_session' : account,
			})

def logout(request):
	del request.session['account_name']
	return render(request , 'home.html')

def register(request) :

	is_register_success = False

	# Fetch register information
	try :
		account_name = request.POST['account_name']
		account_password = request.POST['account_password']
		if '' == account_name or '' == account_password :
			raise KeyError('Invalid account')
	except (KeyError):
		return render(request , 'accounts/register.html' , {
			'is_register_success' : is_register_success ,
			'is_first_time_to_this_page' : True,
			})

	# Encode account password
	md5 = hashlib.md5()
	md5.update(account_password.encode('utf-8'))
	account_password = md5.hexdigest()

	# Create new account
	new_account = Account.create(account_name , account_password)
	try :
		new_account.save()
	except BaseException  :
		return render(request , 'accounts/register.html' , {
			'is_register_success' : is_register_success ,
			'is_first_time_to_this_page' : False,
			})

	# Success		
	is_register_success = True	

	return render(request , 'accounts/login.html' , {
		'is_register_success' : True,
		'is_first_time_to_this_page' : False,
		})

def login(request) :

	is_login_success = False

	# Fetch user configuration
	try:
		account_name = request.POST['account_name']
		account_password = request.POST['account_password']
		if '' == account_name or '' == account_password :
			raise KeyError('Invalid input')
	except(KeyError):
		return render(request , 'accounts/login.html' , {
			'is_login_success' : False,
			'is_register_success' : False,
			'is_first_time_to_this_page' : True,
			})

	# Encode account password
	md5 = hashlib.md5()
	md5.update(account_password.encode('UTF-8'))
	account_password = md5.hexdigest()

	# Account validation
	try:
		account_for_validation = Account.objects.get(_account_name = account_name)
	except Exception, e:
		return render(request , 'accounts/login.html' , {
			'is_login_success' : False,
			'is_register_success' : False,
			'is_first_time_to_this_page' : False,
			})
		
	
	if account_for_validation :
		if account_for_validation.account_passwd == account_password :
			is_login_success = True
			
			request.session['account_name'] = account_name
			request.session.SESSION_EXPIRE_AT_BROWSER_CLOSE = True

			return render(request , 'home.html' , {
			'is_login_success' : is_login_success,
			'user_session' : Account.objects.get(_account_name = account_name),
			})

	return render(request , 'accounts/login.html' , {
			'is_login_success' : False,
			'is_register_success' : False,
			'is_first_time_to_this_page' : False,
			})

def showResume(request) :
	# validate user session
	try:
		account = Account.objects.get(_account_name = request.session['account_name'])
	except Exception, e:
		return render(request , 'accounts/login.html' , {
			'is_login_success' : False,
			'is_register_success' : False,
			'is_first_time_to_this_page' : False,
			})

	return render(request , 'accounts/resume.html',{
		'is_login_success' : True,
		'user_session' : account,
		'request_user' : account,
		'user_skill_list' : account.skill_set.all().order_by('-_skill_proficiency'),
		'user_experience_list' : account.experience_set.all().order_by('-_start_date'),
		})

def showResumeWithID(request, account_id):
	# validate user session
	try:
		account = Account.objects.get(_account_name = request.session['account_name'])
	except Exception, e:
		return render(request , 'accounts/login.html' , {
			'is_login_success' : False,
			'is_register_success' : False,
			'is_first_time_to_this_page' : False,
			})

	try:
		request_account = Account.objects.get(id=account_id)
	except Exception, e:
		return HttpResponseRedirect('/accounts/resume')

	return render(request , 'accounts/resume.html',{
		'is_login_success' : True,
		'user_session' : account,
		'request_user' : request_account,
		'user_skill_list' : request_account.skill_set.all().order_by('-_skill_proficiency'),
		'user_experience_list' : request_account.experience_set.all().order_by('-_start_date'),
		})
	

ILink/accounts/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport"    content="width=device-width, initial-scale=1.0">
	<title>IdeaLink</title>
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" href="/static/css/font-awesome.min.css">
    <link type="image/x-icon" rel="shortcut icon" href="/static/img/favicon.ico" />
	{% block head %}
	{% endblock %}
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap-theme.css" media="screen" >
	<link rel="stylesheet" href="/static/css/home.css">
	<link rel="stylesheet" href="/static/css/projects/avgrund.css">
	 <link rel="stylesheet" href="/static/css/sweetalert.css" />
    {% load static %}  
    <script src="{% static "js/jquery.min.js" %}" ></script>
    {% load static %}
    <script src="{% static "js/sweetalert.min.js" %}"></script>

</head>

<body class="home">
	<!-- Fixed navbar -->
	<div class="navbar navbar-inverse navbar-fixed-top headroom" style="height:100px;" >
		<div class="container">
			<div class="navbar-header">
				<!-- Button for smallest screens -->
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon-bar"></span> 
					<span class="icon-bar"></span> 
					<span class="icon-bar"></span> 
				</button>
				{% if is_login_success %}
				<a class="navbar-brand" style="margin-top:-1px;" href={% url 'accounts:home'%} ><img src="/static/img/logo.png"></a>
				{% else %}
				<a class="navbar-brand" style="margin-top:-1px;" href={% url 'accounts:index' %} ><img src="/static/img/logo.png"></a>
				{% endif %}
			</div>
			{% if is_login_success %}
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav pull-right">
					<li class="active" ><a href="{% url 'accounts:home' %}">Home</a></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Project<b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><a id="find-proj" href="#">Find Project</a></li>
							<li><a id="create-proj" href="#">Create Project</a></li>
							<li class=""><a href={% url 'projects:myProjects' %}>My Projects</a></li>
							<li class=""><a href={% url 'projects:myApplications' %}>My Applications</a></li>
						</ul>
					</li>
					<li><a id="setting" href={% url 'accounts:settingProfile' %}>Setting</a></li>
					<li><a href={% url 'accounts:showResume' %}>{{ user_session.account_name}}</a></li>	
					<li><a class="btn" href={% url 'accounts:logout' %}>LOG OUT</a></li>
				</ul>
			</div><!--/.nav-collapse -->
			{% else %}
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav pull-right">
					<li><a class="btn" href="{% url 'accounts:login'%}">SIGN IN / SIGN UP</a></li> 
				</ul>
			</div><!--/.nav-collapse -->
			{% endif %}
		</div>
	</div> 
	
	<!-- /.navbar -->
	
	{% block content %}
	<div id="large-header" class="large-header demo-3">
		<canvas id="demo-canvas"></canvas>
		<h1 class="main-title"> <!-- spark brilliant --> ideas</span></h1>
	</div>
	<!-- Intro -->
	<div class="container text-center">
		<br> <br>
		<h2 class="thin">The best place to link your idea and power together.</h2>
		<p class="text-muted">
			You got an brilliant idea but don't know how to?
			You got strong energy but don't konw where to?<br>
			NO PROBLEM! It's why you are here.
		</p>
	</div>
	<!-- /Intro-->
	{% load static %}  
  	<script src="{% static "js/home/home.js" %}" ></script>
	{% endblock %}

	{% block footer %}
	<footer id="footer" class="top-space">
		<div class="footer2">
			<div class="container">
				<div class="row">				
					<div class="col-md-6 widget">
						<div class="widget-body">
							<p class="simplenav" stlye="">
								{% if is_login_success %}
								<a href={% url 'accounts:home' %} >Home</a> | 
								<a href="#">Project</a> |
								<a id="setting" href={% url 'accounts:settingProfile' %} >Setting</a> 
								|
								<a id="logout" href={% url 'accounts:logout' %} >Logout</a> 
								{% else %}
								<b><a href={% url 'accounts:register'%}>Sign up</a></b>
								{% endif %}
								| 
								<a href="javascript:scroll(0,0)">
								<span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span>
								</a>
							</p>
						</div>
					</div>
				</div> <!-- /row of widgets -->
			</div>
		</div>
	</footer>	
	{% endblock %}

<!-- create proj -->
	<div style="display: none;">

		<form class="form-horizontal" id="create-proj-form" action={% url 'projects:projectQuickCreate' %} method="POST" style="text-align:center;">
	
		{% csrf_token %}
	 	 <fieldset>
    		<div class="control-group">

	      <!-- Text input-->
		      <label class="control-label" for="input01">Project Name</label>
		      <div class="controls">
		        <input type="text" name = "proj-name" placeholder="project name" class="input-xlarge form-control">
		        <p class="help-block"> </p>
		      </div>
		    </div>

			 <div class="control-group">
		      <!-- Textarea -->
		      <label class="control-label">Description</label>
		      <div class="controls">
		        <div class="textarea">
		              <input name = "description" type="text"  class="form-control"> </input>
		        </div>
		        <p class="help-block"></p>
		      </div>
		    </div>

		     <div class="control-group">
		          <label class="control-label"> </label>
		          <!-- Button -->
		          <div class="controls">
		            <button class="btn btn-success">+</button>
		          </div>
		          <p class="help-block"></p>
		     </div>
		 </div>
		</div>
	 </fieldset>
	 </form>
	</div>
	
<!-- find proj -->
	<div style="display: none;">
	 <form class="form-horizontal" id="find-proj-form" action={% url 'projects:findProject' %} method="POST" style="text-align:center;">
		{% csrf_token %}
	 	 <fieldset>
    		<div class="control-group">
	      <!-- Text input-->
		      <label class="control-label" for="input01">Project Name</label>
		      <div class="controls">
		        <input type="text" name = "search_key" id="search_key" placeholder="Search Key" class="input-xlarge form-control">
		        <p class="help-block"> </p>
		      </div>
		    </div>

		     <div class="control-group">
		          <label class="control-label"> </label>
		          <!-- Button -->
		          <div class="controls">
		            <button type="submit" class="btn btn-success">Search</button>
		          </div>
		          <p class="help-block"></p>
		     </div>
	 	</fieldset>
	 </form>
	</div>
	<!-- to top -->
	<a href="#" onclick="gotoTop();return false;" class="totop"></a>
	<!-- JavaScript libs are placed at the end of the document so the pages load faster -->
  	{% load static %}  
  	<script src="{% static "bootstrap/js/bootstrap.min.js" %}" ></script>
  	{% load static %}  
  	<script src="{% static "js/home/headroom.min.js" %}" ></script>
  	{% load static %}  
  	<script src="{% static "js/home/jQuery.headroom.min.js" %}" ></script>
	{% load static %}  
  	<script src="{% static "js/home/template.js" %}" ></script>

  	{% load static %}
  	<script src="{% static "js/bg/TweenLite.min.js" %}"></script>
  	{% load static %}
  	<script src="{% static "js/bg/EasePack.min.js" %}"></script>
  	{% load static %}
 	<script src="{% static "js/bg/rAF.js" %}"></script>

 	{% load static %}
 	<script src="{% static "js/projects/jquery.avgrund.js" %}"></script>
  	{% block js %}
  	{% endblock %}
  	
	
</body>
</html>