ILink/ILink/urls.py
from django.conf.urls import url , include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/' , include('accounts.urls', namespace='accounts')),
    url(r'^projects/' , include('projects.urls', namespace='projects'))
]

ILink/accounts/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounts'

urlpatterns = [
	url(r'^$' , views.index , name = 'index') ,
	url(r'^register$' , views.register , name = 'register') ,
	url(r'^login$' , views.login , name = 'login') ,
	url(r'^home$' , views.home , name='home'),
	url(r'^index$' , views.logout , name='logout'),
	url(r'^setting$' , views.settingProfile , name='settingProfile'),
	url(r'^setting/experience$' , views.settingExperience , name='settingExperience'),
	url(r'^setting/experience/(?P<experience_id>[0-9]*)$' , views.deleteExperience , name = 'deleteExperience'),
	url(r'^setting/skill$' , views.settingSkill , name='settingSkill'),
	url(r'^setting/skill/(?P<skill_id>[0-9]*)$' , views.deleteSkill , name='deleteSkill'),
	url(r'^resume$' , views.showResume , name='showResume'),
	url(r'^resume/(?P<account_id>[0-9]*)$' , views.showResumeWithID , name='showResumeWithID'),
]

ILink/projects/urls.py
from django.conf.urls import url

from . import views

app_name = 'projects'

urlpatterns = [
	url(r'^$' , views.myProjects , name = 'myProjects') ,
	url(r'^wechattest$' , views.wechattest , name = 'wechattest') ,
	url(r'^wechatredirect$' , views.wechatredirect , name = 'wechatredirect') ,
	url(r'^myApplications$' , views.myApplications , name = 'myApplications') ,
	url(r'^projectsByType/(?P<type>\w*)$' , views.projectsByType , name = 'projectsByType') ,
	url(r'^projectDetail$' , views.projectDetail , name='projectDetail'),
	url(r'^quickCreate$' , views.projectQuickCreate , name = 'projectQuickCreate'),
	url(r'^projectDetail/(?P<project_id>[0-9]*)$' , views.project_details , name = 'projectDetailsById'),
	url(r'^projectDetail/(?P<project_id>[0-9]*)/createTask$' , views.create_task , name = 'createTask'),
	url(r'^projectDetail/(?P<project_id>[0-9]*)/deleteTask/(?P<task_id>[0-9]*)$' , views.delete_task , name = 'deleteTask'),
	url(r'^projectDetail/(?P<project_id>[0-9]*)/addMember$' , views.add_member , name = 'addMember'),
	url(r'^projectDetail/(?P<project_id>[0-9]*)/deleteMember/(?P<member_id>[0-9]*)$' , views.delete_member , name = 'deleteMember'),
	url(r'^findProject$' , views.findProject , name = 'findProject'),
	url(r'^applyProject/(?P<project_id>[0-9]*)$' , views.applyProject , name = 'applyProject'),
	url(r'^applyForProject/(?P<project_id>[0-9]*)$' , views.applyForProject , name = 'applyForProject'),
	url(r'^reviewProject/(?P<project_id>[0-9]*)$' , views.reviewProject , name = 'reviewProject'),
	url(r'^projectDetail/(?P<project_id>[0-9]*)/changeTask/(?P<task_id>[0-9]*)$' , views.change_task , name = 'changeTask'),
	url(r'^projectDetail/(?P<project_id>[0-9]*)/addApplicant/(?P<member_id>[0-9]*)$' , views.addApplicant , name = 'addApplicant'),
	url(r'^projectDetail/(?P<project_id>[0-9]*)/deleteApplicant/(?P<member_id>[0-9]*)$' , views.deleteApplicant , name = 'deleteApplicant'),

]

ILink/projects/models.py
from __future__ import unicode_literals

from django.db import models
from datetime import datetime

from accounts.models import Account

class WechatQRCode(models.Model) :
	account = models.OneToOneField(
		Account,
		on_delete = models.CASCADE,
		)

	wechat_openid = models.CharField(max_length=100,primary_key=True)
	qrcode_url = models.CharField(max_length=100,blank=True)

	@classmethod
	def create(cls,account,openid):
		return cls(account = account, wechat_openid = openid)

class Project(models.Model) :
	"""
	Project information , many to many relationship to account

	"""
	
	# Basic info for project
	project_name = models.CharField(max_length=50, unique=True)

	project_description = models.CharField(max_length=140,blank=True)
	project_start_date = models.CharField(max_length=50,blank=True)
	project_expire_date = models.CharField(max_length=50,blank=True)
	project_status = models.CharField(max_length=20)

	project_owner = models.ForeignKey(
		Account,
		on_delete=models.CASCADE
		)
	project_members = models.ManyToManyField(
		Account,
		related_name='%(app_label)s_%(class)s_related')
	project_applicants = models.ManyToManyField(
		Account,
		related_name='%(app_label)s_applicant_related')

	@classmethod
	def create(cls, account, name, description):
		
		return cls(project_owner = account, project_name = name , project_description = description,project_expire_time = datetime.now().strftime("%Y-%m-%d"))

	# Modification update
	def update_project(self,proj_name,proj_description,proj_deadline,proj_status):
		self.project_name = proj_name
		self.project_description = proj_description
		self.project_expire_date = proj_deadline
		self.project_status = proj_status

	def __str__(self) :
		project_info = 'Project: ' + self.project_name
		return project_info
	__repr__ = __str__	



# Task information , many to one relationship to Project
class Task(models.Model) :
	"""
	Task information

	"""
	project = models.ForeignKey(
		Project,
		on_delete = models.CASCADE
		)

	task_name = models.CharField(max_length=50, unique=True)
	task_description = models.CharField(max_length=140,blank=True)
	task_start_date = models.DateField(blank=True)
	task_expire_time = models.DateField(blank=True)
	task_status = models.CharField(max_length=20)

	# members involved in this task , many to many relationship to accounts.Account
	task_members = models.ManyToManyField(Account)
	
	@classmethod
	def create(cls, name, description):
		return cls(task_name = name, task_description = description)
	def change_status(self,status):
		self.task_status = status

	

# Tag information , modified by administrator , many to many relationship to project
class Tag(models.Model) :
	"""
	Tag information

	"""
	tag_name = models.CharField(max_length=50,unique=True)
	tag_description = models.CharField(max_length=80 , unique=True)

	# Projects envolved in this tag
	tag_project = models.ManyToManyField(Project)


	# properties update
	def update_tag(self, name, description):
		self.tag_name = name
		self.tag_description = description

	# Representations
	def __str__(self):
		return 'Tag:' + tag_name + " --- " + tag_description
	__repr__ = __str__ 

ILink/projects/views.py
#-*- coding:utf-8 -*-

from django.shortcuts import render
from datetime import datetime
import hashlib
from datetime import timedelta
from accounts.models import Account
from django.http import HttpResponseRedirect, HttpResponseBadRequest, HttpResponse
from .models import Project, WechatQRCode

import sys
import os
reload(sys)
sys.setdefaultencoding('utf8')

from django.views.decorators.csrf import csrf_exempt
from wechat_sdk import WechatConf, WechatBasic
from wechat_sdk.exceptions import ParseError
from wechat_sdk.messages import ImageMessage, TextMessage

# Wechat configurations
conf = WechatConf(
	token = 'ILinkProjToken',
	appid = 'wx078801c8b39da1c2',
	appsecret = '579998602563a35b67d20ab6228e33b3',
	encrypt_mode = 'save',
	)


# Create your views here.
@csrf_exempt
def wechattest(request):

	signature = request.GET.get('signature')
	timestamp = request.GET.get('timestamp')
	nonce = request.GET.get('nonce')
	wechat_instance = WechatBasic(conf = conf)

	if not wechat_instance.check_signature(signature = signature, timestamp = timestamp, nonce = nonce) :
		return HttpResponseBadRequest('Verify Failed')
	else :
		if request.method == 'GET' :
			response = request.GET.get('echostr', 'err')
		else :
			try:
				wechat_instance.parse_data(request.body)
				message = wechat_instance.get_message()
				wechat_user_openid = wechat_instance.message.source

				# res = wechat_instance.create_qrcode({
				# 		    "expire_seconds": "QR_LIMIT_SCENE", 
				# 		    "action_name": "QR_SCENE", 
				# 		    "action_info": {
				# 		        "scene": {
				# 		            "scene_id": 123
				# 		        }
				# 		    }
				# 		})
				
				# response = wechat_instance.show_qrcode(res['ticket'])

				# with open('tmpfile', 'wb') as fd:
				#     for chunk in response.iter_content(1024):
				#         fd.write(chunk)
				

				if isinstance(message, ImageMessage) :
					try:
						link = WechatQRCode.objects.get(wechat_openid = wechat_user_openid)
						link.qrcode_url = message.picurl
						link.save()
						
						response = wechat_instance.download_media(message.media_id)
						# import pdb; pdb.set_trace()
						# filename = os.path.join(os.path.pardir,'/static/img/' + link.account.account_name + '.jpeg')

						with open('ILink/static/img/' + link.account.account_name + '.jpeg', 'wb') as fd :
							for chunk in response.iter_content(1024) :
								fd.write(chunk)


						reply_text = '二维码上传成功'

					except Exception, e:
						reply_text = '请先绑定帐号\n\n绑定ILink帐号，请使用 - 为分隔符输入帐号密码\n上传个人微信二维码，请直接发送图片'
					
				elif isinstance(message, TextMessage) :
					content = message.content

					if content.find("-") > -1 :
						# User varification
						account, passwd = content.split("-")

						# Encode account password
						md5 = hashlib.md5()
						md5.update(passwd.encode('utf-8'))
						passwd = md5.hexdigest()

						# Account validation
						try:
							account_for_validation = Account.objects.get(_account_name = account)
						except Exception, e:
							reply_text = '绑定ILink帐号，请使用 - 为分隔符输入帐号密码\n上传个人微信二维码，请直接发送图片'
							
						# import pdb; pdb.set_trace()
						if account_for_validation :
							if account_for_validation.account_passwd == passwd :
								try:
									link = WechatQRCode.objects.get(wechat_openid = wechat_user_openid)
									link.account = account_for_validation
									reply_text = '重新绑定ILink帐号成功'

								except Exception, e:
									newlink = WechatQRCode.create(account = account_for_validation, openid=wechat_user_openid)
									newlink.save()
									reply_text = '绑定ILink帐号成功'
								

							else :
								reply_text = '绑定ILink帐号验证失败'	


					else :
						reply_text = '绑定ILink帐号，请使用 - 为分隔符输入帐号密码\n上传个人微信二维码，请直接发送图片'

				else :
					reply_text = '绑定ILink帐号，请使用 - 为分隔符输入帐号密码\n上传个人微信二维码，请直接发送图片'

				response = wechat_instance.response_text(content = reply_text)
			except ParseError:
				return HttpResponseBadRequest('Invalid XML data.')
			
	return HttpResponse(response, content_type = 'application/xml')

@csrf_exempt
def wechatredirect(request):
	pass

def index(request) :
	return render(request , 'projects/myProjects.html')

def myProjects(request) :
	press_create = False
	create_project_succeed = False
	# validate user session
	try:
		account = Account.objects.get(_account_name = request.session['account_name'])
	
	except Exception, e:
		return render(request , 'accounts/login.html' , {	
			'is_login_success' : False,
			'is_register_success' : False,
			'is_first_time_to_this_page' : False,
			})

	return render(request , 'projects/myProjects.html',{
		'is_login_success' : True,
		'user_session' : account,
		'press_create' : False,
		'create_project_succeed' : False,
		'target_projects' : account.project_set.all() | Project.objects.filter(project_members__id = account.id)
		})

def myApplications(request):
	# validate user session
	try:
		account = Account.objects.get(_account_name = request.session['account_name'])
	
	except Exception, e:
		return render(request , 'accounts/login.html' , {	
			'is_login_success' : False,
			'is_register_success' : False,
			'is_first_time_to_this_page' : False,
			})


	# import pdb; pdb.set_trace()
	result = Project.objects.filter(project_applicants__id = account.id)
	find_project_success = True
	return render(request , 'projects/findProject.html',{
		'is_login_success' : True,
		'find_project_success' : find_project_success,
		'user_session' : account,
		'results' : result
		})


def projectsByType(request, type):
	press_create = False
	create_project_succeed = False
	# validate user session
	try:
		account = Account.objects.get(_account_name = request.session['account_name'])
	except Exception, e:
		return render(request , 'accounts/login.html' , {	
			'is_login_success' : False,
			'is_register_success' : False,
			'is_first_time_to_this_page' : False,
			})

	if type == 'All' :
		target_projects = account.project_set.all() | Project.objects.filter(project_members__id = account.id)
	elif type == 'Own' :
		target_projects = account.project_set.all()
	elif type == 'Member' :
		target_projects = Project.objects.filter(project_members__id = account.id)	
	else :
		target_projects = account.project_set.all() | Project.objects.filter(project_members__id = account.id)

	return render(request , 'projects/myProjects.html',{
		'is_login_success' : True,
		'user_session' : account,
		'press_create' : False,
		'create_project_succeed' : False,
		'target_projects' : target_projects
		})

def projectDetail(request) :
	# validate user session
	try:
		account = Account.objects.get(_account_name = request.session['account_name'])
	except Exception, e:
		return render(request , 'accounts/login.html' , {	
			'is_login_success' : False,
			'is_register_success' : False,
			'is_first_time_to_this_page' : False,
			})
	return render(request , 'projects/projectDetail.html',{
		'is_login_success' : True,
		'user_session' : account,
		})

def project_details(request , project_id):
	# validate user session
	try:
		account = Account.objects.get(_account_name = request.session['account_name'])
	except Exception, e:
		return render(request , 'accounts/login.html' , {
			'is_login_success' : False,
			'is_register_success' : False,
			'is_first_time_to_this_page' : False,
			})

	# Fetch project info
	# import pdb; pdb.set_trace()
	current_project = Project.objects.get(id=project_id)
	pending_tasks = current_project.task_set.filter(task_status = 'Pending')
	underway_tasks = current_project.task_set.filter(task_status = 'Underway')
	finished_tasks = current_project.task_set.filter(task_status = 'Finished')
	


	return render(request , 'projects/projectDetail.html', {
		'is_login_success' : True,
		'user_session' : account,
		'current_project' : current_project,
		'pending_tasks' : pending_tasks,
		'underway_tasks' : underway_tasks,
		'finished_tasks' : finished_tasks,
		'appid' : conf.appid
		})

def create_task(request, project_id):
	# validate user session
	try:
		account = Account.objects.get(_account_name = request.session['account_name'])
	except Exception, e:
		return render(request , 'accounts/login.html' , {
			'is_login_success' : False,
			'is_register_success' : False,
			'is_first_time_to_this_page' : False,
			})
	# Fetch project info and create new task
	try:
		current_project = Project.objects.get(id=project_id)

		task_name = request.POST['task_name']
		task_description = request.POST['task_description']

		current_project.task_set.create(task_name = task_name, task_description= task_description, task_start_date = datetime.now(),
			task_expire_time = (datetime.now() + timedelta(days=30)), task_status = 'Pending')
	except Exception, e:
		return HttpResponseRedirect('/projects/projectDetail/' + project_id)
	return HttpResponseRedirect('/projects/projectDetail/' + project_id)

def delete_task(request, project_id, task_id):
	# validate user session
	try:
		account = Account.objects.get(_account_name = request.session['account_name'])
	except Exception, e:
		return render(request , 'accounts/login.html' , {
			'is_login_success' : False,
			'is_register_success' : False,
			'is_first_time_to_this_page' : False,
			})
	# Fetch project info and create new task
	try:
		
		current_project = Project.objects.get(id=project_id)
		current_task = current_project.task_set.filter(id=task_id)
		for task in current_task :
			task.delete()
	except Exception, e:
		return HttpResponseRedirect('/projects/projectDetail/' + project_id)
	return HttpResponseRedirect('/projects/projectDetail/' + project_id)
	
def projectQuickCreate(request):
	press_create = True
	create_project_succeed = False
	# validate user session
	try:
		account = Account.objects.get(_account_name = request.session['account_name'])
	except Exception, e:
		return render(request , 'accounts/login.html' , {	
			'is_login_success' : False,
			'is_register_success' : False,
			'is_first_time_to_this_page' : False,
			})

	
	# check user input
	try:
		proj_name = request.POST['proj-name']

ILink/projects/templates/projects/applyProject.html
{% extends 'home.html' %}

{% block head %}
    <link rel="stylesheet" href="/static/css/projects/buttons.css">
    <link href="/static/css/projects/style.css" rel="stylesheet">
    <link href="/static/css/projects/project.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/css/projects/jquery-ui.min.css">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/font-awesome.min.css">
    <!-- 只有使用字体图标时才需要加载 Font-Awesome -->
    <link href="http://cdn.bootcss.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

{% endblock %}


{% block content %}

<header id="head" class="secondary"></header><br/>

<div id="large-header" class="container" >
    <div class="row">
            <div class="col-md-6">
                <h3>-Project Info-</h3>
            </div>
    </div>

    
    <div class="row">
        <div class="col-md-offset-3 col-md-6 " align="center">
              <table class="table ">
                   <tbody>
                      <tr class="success">
                        <td align="center">
                            <span class="fa-stack fa-lg fa-3x">
                            <i class="fa fa-circle fa-stack-2x"></i>
                            <i class="fa fa-flag-checkered fa-stack-1x fa-inverse"></i>
                            </span>{{current_project.project_name}}
                        </td>
                      </tr>
                      <tr>
                        <td>Strat Date: <strong>{{current_project.project_start_date}}</strong></td>
                      </tr>
                      <tr>
                        <td>Deadline: <strong>{{current_project.project_expire_time}}</strong></td>
                      </tr>
                      <tr>
                        <td>Status: <strong>{{current_project.project_status}}</strong></td>
                      </tr>
                      <tr>
                        <td>Description: <strong>{{current_project.project_description}}</strong></td>
                      </tr>
                     </tbody>
                </table>
            </div>
        </div>
        <p class="help-block"></p>
         <div class="row">
            <div class="col-md-offset-4 col-md-4" align="center" >
                <a class="btn btn-success" href={% url 'projects:applyForProject' current_project.id %}>APPLY</a>
            </div>
            
         </div>

{% endblock %}

{% block footer %}
    <footer id="footer" class="top-space">
      <nav class="navbar-default navbar-fixed-bottom">
        <div class="footer2">
            <div class="container">
                <div class="row">               
                    <div class="col-md-6 widget">
                        <div class="widget-body">
                            <p class="simplenav" stlye="">
                                {% if is_login_success %}
                                <a href={% url 'accounts:home' %} >Home</a> | 
                                <a href="#">Project</a> |
                                <a id="setting" href={% url 'accounts:settingProfile' %} >Setting</a> 
                                |
                                <a id="logout" href={% url 'accounts:logout' %} >Logout</a> 
                                {% else %}
                                <b><a href={% url 'accounts:register'%}>Sign up</a></b>
                                {% endif %}
                                | 
                                <a href="javascript:scroll(0,0)">
                                <span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span>
                                </a>
                            </p>
                        </div>
                    </div>
                </div> <!-- /row of widgets -->
            </div>
        </div>
     </nav>
    </footer>   
{% endblock %}


{% block js %}
    {% load static %}
    <script src="{% static "bootstrap/js/bootstrap-datetimepicker.js" %}"></script>
    {% load static %}
    <script src="{% static "js/projects/jquery-ui.min.js" %}"></script>
    {% load static %}  
    <script src="{% static "js/projects/buttons.js" %}"></script>
    {% load static %}
    <script src="{% static "js/projects/project.js" %}"></script>
    {% load static %}
    <script src="{% static "js/projects/icheck.js" %}"></script>
    {% load static %}
    <script src="{% static "js/projects/jquery.icheck.js" %}"></script>
    
  
{% endblock %}

ILink/projects/templates/projects/myProjects.html
{% extends 'home.html' %}

{% block head %}
    <link rel="stylesheet" href="/static/css/projects/buttons.css">
    <link href="/static/css/projects/style.css" rel="stylesheet">
    <link href="/static/css/projects/project.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/css/projects/jquery-ui.min.css">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/font-awesome.min.css">
    <!-- 只有使用字体图标时才需要加载 Font-Awesome -->
    <link href="http://cdn.bootcss.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    
{% endblock %}


{% block content %}

{% if press_create == True %}
    {% if create_project_succeed == False %}
    <script>
      swal("Oops...", "Create Project unsuccessfully!", "error");
    </script>
    {% endif %}
    {% if create_project_succeed == True %}
    <script>
      swal("Success", "Create project successfully!", "success");
    </script>
    {% endif %}
{% endif %}

<header id="head" class="secondary"></header><br/>

<div id="large-header" class="container" >
    <div class="row">
            <div class="col-md-6">
                <h3>-My Projects-</h3>
            </div>
            <div class="col-md-offset-3 col-md-3"align="center">
                  <span class="button-dropdown button-dropdown-inverse" data-buttons="dropdown">
                    <a href="#" class="button button-inverse" >
                        <i class="fa "></i> Categories <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="button-dropdown-list is-below">
                        <li class="button-dropdown-divider">
                            <a href={% url 'projects:projectsByType' 'All' %}>All</a>
                        </li>
                        <li class="button-dropdown-divider">
                            <a href={% url 'projects:projectsByType' 'Own' %}>Own</a>
                        </li>
                        <li>
                            <a href={% url 'projects:projectsByType' 'Member' %}>Member</a>
                        </li>
                    </ul>
                  </span>
        </div>
    </div>

    <div class="row">
        {% for project in target_projects %}
        <div class="col-md-4 "align="center" >
            <a href={% url 'projects:projectDetailsById' project.id%} class="thumbnail">
                    <span class="fa-stack fa-lg fa-3x">
                        <i class="fa fa-circle fa-stack-2x"></i>
                        <i class="fa fa-flag fa-stack-1x fa-inverse"></i>
                    </span>
                    <strong class="text-info">{{project.project_name}}</strong>
            </a>
        </div>
        {% endfor %}    
        <div class="col-md-4" align="center" >

            <a id="modal-1" href="#modal-container-1"  class="btn" data-toggle="modal" class="thumbnail" >
                <button class="button button-circle button-jumbo"><i class="fa fa-plus"></i></button>
                <p>Create A Project</p>
            </a>

            
            <!--弹出框-->
            <form class="form-horizontal" id="create-proj-form" action={% url 'projects:projectQuickCreate' %} method="POST" style="text-align:center;">
                {% csrf_token %}
                <fieldset>
                <div class="modal fade" id="modal-container-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            </div>
                            <div class="modal-body">
                                <div class="tabbable" id="tabs-299950">
                                    <ul class="nav nav-tabs">
                                        <li class="active">
                                            <a href="#information" data-toggle="tab">Create A Project</a>
                                        </li>
                                    </ul>
                                    <div class="tab-content">
                                        <div class="tab-pane active" id="information">
                                            <div align="left">
                                            <h4 >Project Name</h4></div>
                                            <input name="proj-name" type="text" id="name" placeholder="Project name" style="height:40px;width:550px"
                                                   onclick="if(value==defaultValue){value='';this.style.color='#000'}"
                                                   onBlur="if(!value){value=defaultValue;this.style.color='#999'}" style="color:#999" />
                                            <div align="left">
                                                <h4 >Details</h4></div>
                                            <input name="description" type="text" id="describe" placeholder="Project description" 
                                                   style="height:120px;width:550px"
                                                   onclick="if(value==defaultValue){value='';this.style.color='#000'}"
                                                   onBlur="if(!value){value=defaultValue;this.style.color='#999'}" 
                                                   style="color:#999" />
                                        </div>
                                    </div>
                                </div>

                                <script>
                                    $(function () {
                                        $('#myTab li:eq(1) a').tab('show');
                                    });
                                </script>
                            </div>

                            <div class="modal-footer">

                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                <button id="create-btn" type="submit" class="btn btn-primary">Create</button>
                                
                            </div>
                        </div>
                    </div>
                </div>
             </fieldset>
             </form>
            <!--弹出框-->
        </div>
    
    </div>
{% endblock %}

{% block footer %}
    <footer id="footer" class="top-space">
      <nav class="navbar-default navbar-fixed-bottom">
        <div class="footer2">
            <div class="container">
                <div class="row">               
                    <div class="col-md-6 widget">
                        <div class="widget-body">
                            <p class="simplenav" stlye="">
                                {% if is_login_success %}
                                <a href={% url 'accounts:home' %} >Home</a> | 
                                <a href="#">Project</a> |
                                <a id="setting" href={% url 'accounts:settingProfile' %} >Setting</a> 
                                |
                                <a id="logout" href={% url 'accounts:logout' %} >Logout</a> 
                                {% else %}
                                <b><a href={% url 'accounts:register'%}>Sign up</a></b>
                                {% endif %}
                                | 
                                <a href="javascript:scroll(0,0)">
                                <span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span>
                                </a>
                            </p>
                        </div>
                    </div>
                </div> <!-- /row of widgets -->
            </div>
        </div>
     </nav>
    </footer>   
{% endblock %}


{% block js %}
    {% load static %}
    <script src="{% static "bootstrap/js/bootstrap-datetimepicker.js" %}"></script>
    {% load static %}
    <script src="{% static "js/projects/jquery-ui.min.js" %}"></script>
    {% load static %}  
    <script src="{% static "js/projects/buttons.js" %}"></script>
    {% load static %}
    <script src="{% static "js/projects/project.js" %}"></script>
    {% load static %}
    <script src="{% static "js/projects/icheck.js" %}"></script>
    {% load static %}
    <script src="{% static "js/projects/jquery.icheck.js" %}"></script>
    
  
{% endblock %}